package model;
// Generated Sep 25, 2017 10:03:09 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Osiguranolice generated by hbm2java
 */
@Entity
@Table(name="osiguranolice"
    ,catalog="domzdravlja"
)
public class Osiguranolice  implements java.io.Serializable {


     private int userId;
     private Korisnik korisnikByNadlezniLekar;
     private Korisnik korisnikByUserId;
     private String jmbg;

    public Osiguranolice() {
    }

	
    public Osiguranolice(Korisnik korisnikByUserId, String jmbg) {
        this.korisnikByUserId = korisnikByUserId;
        this.jmbg = jmbg;
    }
    public Osiguranolice(Korisnik korisnikByNadlezniLekar, Korisnik korisnikByUserId, String jmbg) {
       this.korisnikByNadlezniLekar = korisnikByNadlezniLekar;
       this.korisnikByUserId = korisnikByUserId;
       this.jmbg = jmbg;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="korisnikByUserId"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="userId", unique=true, nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="nadlezniLekar")
    public Korisnik getKorisnikByNadlezniLekar() {
        return this.korisnikByNadlezniLekar;
    }
    
    public void setKorisnikByNadlezniLekar(Korisnik korisnikByNadlezniLekar) {
        this.korisnikByNadlezniLekar = korisnikByNadlezniLekar;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Korisnik getKorisnikByUserId() {
        return this.korisnikByUserId;
    }
    
    public void setKorisnikByUserId(Korisnik korisnikByUserId) {
        this.korisnikByUserId = korisnikByUserId;
    }

    
    @Column(name="jmbg", nullable=false, length=20)
    public String getJmbg() {
        return this.jmbg;
    }
    
    public void setJmbg(String jmbg) {
        this.jmbg = jmbg;
    }




}


