package model;
// Generated Sep 25, 2017 10:03:09 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pregled generated by hbm2java
 */
@Entity
@Table(name="pregled"
    ,catalog="domzdravlja"
)
public class Pregled  implements java.io.Serializable {


     private int pregledId;
     private Korisnik korisnikByOsiguranoLice;
     private Korisnik korisnikByMedicinskaSestra;
     private Date termin;
     private String lokacija;

    public Pregled() {
    }

	
    public Pregled(int pregledId, Korisnik korisnikByOsiguranoLice, Korisnik korisnikByMedicinskaSestra, Date termin) {
        this.pregledId = pregledId;
        this.korisnikByOsiguranoLice = korisnikByOsiguranoLice;
        this.korisnikByMedicinskaSestra = korisnikByMedicinskaSestra;
        this.termin = termin;
    }
    public Pregled(int pregledId, Korisnik korisnikByOsiguranoLice, Korisnik korisnikByMedicinskaSestra, Date termin, String lokacija) {
       this.pregledId = pregledId;
       this.korisnikByOsiguranoLice = korisnikByOsiguranoLice;
       this.korisnikByMedicinskaSestra = korisnikByMedicinskaSestra;
       this.termin = termin;
       this.lokacija = lokacija;
    }
   
     @Id 

    
    @Column(name="pregledId", unique=true, nullable=false)
    public int getPregledId() {
        return this.pregledId;
    }
    
    public void setPregledId(int pregledId) {
        this.pregledId = pregledId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="osiguranoLice", nullable=false)
    public Korisnik getKorisnikByOsiguranoLice() {
        return this.korisnikByOsiguranoLice;
    }
    
    public void setKorisnikByOsiguranoLice(Korisnik korisnikByOsiguranoLice) {
        this.korisnikByOsiguranoLice = korisnikByOsiguranoLice;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="medicinskaSestra", nullable=false)
    public Korisnik getKorisnikByMedicinskaSestra() {
        return this.korisnikByMedicinskaSestra;
    }
    
    public void setKorisnikByMedicinskaSestra(Korisnik korisnikByMedicinskaSestra) {
        this.korisnikByMedicinskaSestra = korisnikByMedicinskaSestra;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="termin", nullable=false, length=19)
    public Date getTermin() {
        return this.termin;
    }
    
    public void setTermin(Date termin) {
        this.termin = termin;
    }

    
    @Column(name="lokacija", length=20)
    public String getLokacija() {
        return this.lokacija;
    }
    
    public void setLokacija(String lokacija) {
        this.lokacija = lokacija;
    }




}


