package model;
// Generated Sep 25, 2017 10:03:09 AM by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Uloge generated by hbm2java
 */
@Entity
@Table(name="uloge"
    ,catalog="domzdravlja"
)
public class Uloge  implements java.io.Serializable {


     private int idUloge;
     private String nazivUloge;
     private List<Korisnik> korisniks =new ArrayList<>();

    public Uloge() {
    }

	
    public Uloge(int idUloge, String nazivUloge) {
        this.idUloge = idUloge;
        this.nazivUloge = nazivUloge;
    }
    public Uloge(int idUloge, String nazivUloge, List<Korisnik> korisniks) {
       this.idUloge = idUloge;
       this.nazivUloge = nazivUloge;
       this.korisniks = korisniks;
    }
   
     @Id 

    
    @Column(name="idUloge", unique=true, nullable=false)
    public int getIdUloge() {
        return this.idUloge;
    }
    
    public void setIdUloge(int idUloge) {
        this.idUloge = idUloge;
    }

    
    @Column(name="nazivUloge", nullable=false, length=20)
    public String getNazivUloge() {
        return this.nazivUloge;
    }
    
    public void setNazivUloge(String nazivUloge) {
        this.nazivUloge = nazivUloge;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="uloges")
    public List<Korisnik> getKorisniks() {
        return this.korisniks;
    }
    
    public void setKorisniks(List<Korisnik> korisniks) {
        this.korisniks = korisniks;
    }




}


